# Generated by Django 4.2.16 on 2025-07-05 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de observación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la observación')),
                ('imagen_base64', models.TextField(blank=True, null=True, verbose_name='Imagen en Base64')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario que creó la observación')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='vehiculos.vehiculo', verbose_name='Vehículo asociado')),
            ],
            options={
                'verbose_name': 'Observación de vehículo',
                'verbose_name_plural': 'Observaciones de vehículos',
                'ordering': ['-fecha'],
            },
        ),
    ]
