# Generated by Django 4.2.16 on 2025-07-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_observacionvehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_base64', models.TextField(verbose_name='Imagen en Base64')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la imagen')),
                ('observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.observacionvehiculo', verbose_name='Observación asociada')),
            ],
        ),
    ]
