# Generated by Django 4.2.16 on 2025-07-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_imagenobservacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='observacionvehiculo',
            name='imagenes_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Imágenes adicionales en Base64 (JSON)'),
        ),
    ]
