# Generated by Django 4.2.16 on 2025-07-06 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
    ]
