# Generated by Django 4.2.16 on 2025-07-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
